# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔
 

# SubNav
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /ca.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  奥巴马的博客: http://xschao.com/aobama
  卡卡的美丽传说: http://xschao.com/kaka
  本泽马的博客: http://xschao.com/benzema
  吉格斯的博客: http://xschao.com/jigesi
  习大大大不同: http://xschao.com/xidada
  托蒂的博客: http://xschao.com/tuodi

#是否开启“关于我”。
#不开启——
aboutme: true
#开启——
aboutme:  do it do it get it..... 依然是一个 blank